name: Flask App Tests

on:
    pull_request:
        branches:
            - main  # This workflow triggers on pull requests to the main branch.

jobs:
    test:
        runs-on: ubuntu-latest  # Specifies the OS for the virtual environment.

        # Setting up a matrix to run tests on multiple Python versions.
        strategy:
            matrix:
                python-version: [3.8, 3.9]

        # Environment variables for the job
        env:
            MODE: "dev"  # Environment mode, consider using GitHub secrets for sensitive data.

        steps:
            # Checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v3  # Corrected the typo in the checkout action.

            # Set up the Python environment based on the matrix.
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}  # Uses the Python version from the matrix.

            # Install the required dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip  # Upgrade pip to the latest version.
                pip install -r requirements.txt  # Install dependencies from the requirements file.
              shell: bash  # Specifies the shell, though it's optional, it's good practice.

            # Run the tests
            - name: Test App Code
              run: python ./main_test.py  # Runs the test file.
              shell: bash  # Specifies the shell, though it's optional, it's good practice.
